language: node_js
cache: yarn
branches:
  only:
    - master
    - production
before_script:
  - chmod +x ./scripts/ci_build.sh
script:
  - yarn lint
  - yarn flow
  - yarn test
  - ./scripts/ci_build.sh
deploy:
  - provider: s3
    access_key_id: "jVOdxe4sESXVF5pqpSxhVVy54a+CbYj4CDiIp1EFUlLaK7EXYNiwAINZp9qPlhjOMhwesaY3qzrAqT8JndaXzh7roKyGrEXem2bIGTKm28sSQj/drwJO02gqsUxS9GR5Dj8YnCvk9WU1dkj40JvuPP3LrpZnqpNh7nGgRWA+LiFnyGIuocdXDUT3qX3D+uQ3RssYZf/zXnPKSeL0NuYHD7X0mLvbrvSXHOwNPHpoReWLsEQ6B97qFl6pPUiLobB/MTKfBxI7LEq485k/aadz5SavFtYN0PS7WBUzGs1KC6uNXsxOCXBsMh0rL7ReTq+QW+IEXmKc9fOvN3WiqssJ+DIP6U15aJCzi7QboN6/ZhigKOVUPGXcVB6nwQ1Lt42V9YPLBuF2HoB7MZv6gZcTVyYJHFQXd0E9OMLGLXf3SJSANn8DxPqmzSTkPsww+oysen2rBRh3zAT0y6y5nNOVLLGkLNDphvRhL+BbqhjUV9HSpSo+Bqgm+rD6iL9rFvyILg50QHlnr6zwSmbbWZBbqqwNdDY8wP9PMtGgbslGtjMIpK75c60YeeH3N8tOS1D5oNspPT6cZ1TvUO13NHhFQuMxe2RoxGCthavVQAaVMN5yc+5oX2nGPVshjbZY3izLQRbOzzZBiMYWrsnaw0n8E1LcBth57zJjBlnwuwUL/Qg="
    secret_access_key: "uYOfsn9BPBsw/3f0PmTKGWklbC4iRiRKJJGG2uAf27mFTYdZ/K0Fekg+6CfA8sZwoZAH2tEo2VV/anUQtlyEb0gtTQj9KDPKXRzvVnTHtQAZqCxX7pMe5EiJXmzU+0t/b/6yJnj8n7svCYmq8J8qShN0C2UQnXYwphEpLrbrWC8GVV1hji9nJdMDerl1N5sOKDMTiAjngfjNKm0SiEZeX5ydNIw/x3z/aIe8OjKej7dkgafT7nuKsEgwMlk9Zl/GmvZt2j19IXquwdHTkwpV6/2RrG77YQDmMmV6UvfSrk+oBtfi1EJQZHlrydPwwquDy+nBDwvs5mTiJHRQBfIeqcHhvYxwzeaMMPDMgju42imWFLo+j1meZNwVTjetFG1sGUScYcRb9NhjjoWf+X91O7OFZZ1ZQCbvFZiKxcorMr/youY6dPvgop51DuUv/xK+IYUBQ13FnjKCpEEMOWV5zYiTzJ7OHDkCYNqd1VHH7BN3l6PaJrjT+hMI7HWfjQhs2qFYZK/rTTBAX3aXUU2BqdODWcBCmEgqYKb/jryQmoPRyW579oqtVnh8+bpaoB0THAlJh8rO8B3uqWe/9LO/ssc4JoP1RgpLt0zhH26inE0nn+t2hTOpefbKin1d3UtRTTG2ONM5rittCtd44nvp9dVTh/kBiuLyhPLe02lY1wM="
    bucket: staging.legislated.org
    region: us-east-2
    local_dir: dist
    skip_cleanup: true
    on:
      branch: master
  - provider: s3
    access_key_id: "v55SZvbLL80Edrbv8FdS39SKiMwGYJvvLOuEmYsST+WLGQQuKuN19eu50eXOyeNwg0tvRl871a+5FvPlSoQmqLlfvHCIeTBrEdo3nS4usYeWhIcuDQzhHtIJzqKsZtwWQNje3r6iG+5nULilynMdAAJrF7EUNXw+0hDzT2JGbRZOeIShS4LapVrpGXO1q1nHsf+XxU3XhL9RZlXZ5fH0bg01KTLk5HIjcsweILJgDBIYhmTThlnGX7lEXToEZboQ8nO/An8mW48+pLj+4jTlPT+7hU7lc0zp6/2XWTDJWRtYShKwVfZe3ycbwCfGRIl/pUopflnGJ4J5iu/fiVsAYVUQq6qks6G2C6YyxpwQ67CN/S73izbG9+pRF9mIAuhV5xMOtEuqWojIKfs+KsaXfFAaubg0BXUbfZKFqwH/WT9hwKb0xkfLns44GruySJP3HFQhCUq82RQOiP+fbktg8gzLwVQgGiZgThxq+yuEABQzkXCctPYFc/gfImb2tM0EzoDqk22A3+sptasaD2DvB/CdUjwy66itrOF1oXoAKK2HRF1zX/o11yu+O0s7FPhXOL+NSAQM5WKrhMfqC0qZdzooh4DJ/vklQbTjaUVnRNXKIEDNmDREXfGO+bmbN5qG6F9r9XMngtcGEz+quZkZccoWl6+YnAw82f4PYpUVOI0="
    secret_access_key: "Vo10NZ5oCEVxPNJJdbW7I3K9QqDd0J412kK4UE5kLRgX0LHgLl5fJhY7EtqTi9pPQf+jKKr9Td1Auu2z36Uf2yX7xqyRylY5A727aZECtoJkoPL2soyXc3TFpEPpREmGh8rDocGK/smnI66RNb4/h7BcE/ETCqzP73HZRBMkL5/1nXRjdPkAIHXFBq8W6MvynnFBbuMx0gH0D5UaJAHhPRlBQhlE68CGXuzF5fntd6Q78wgmRbqEx2mZhgqvU6UWiP11yna5wvf5HcgSWkp17bm0fABEFhi1gE2qdtpsWF48oqFq5PWmRWX+laSSJf7qf8epXwC6TXr9n6WRmXiEWHe4w3kdpnS+odzPdgR8XAClu9qt7ZOoYdaLQz2hgGRlqdq0Dvks8mftPZQvWPbNKWL9YjZnPPfE24Rzmb5B8lm85ndsFpBVrL5NTumcHeI/ASzqs24wV4cquyoDeZ8hKIQkbVkLo+Dz7KrTRkNiFAV20/X8eAvl/cKMdiOA5J0gGLajD0Ov0qkYZmw/5Japn3OkcrWJzKpxliUqQVrNWi5/1DSkg4jKaAx9IKGDZ67bi8qd/RQVOYXF0Dn7vC3/TgRBN2/8/RrylB7hskNyx+MJje+KDukvuwcwKl2GoF8/2n2pGdE1GrVTXRWKui/WcBLHnvDEaqSaLDbeGmtkz/Y="
    bucket: legislated.org
    region: us-east-2
    local_dir: dist
    skip_cleanup: true
    on:
      branch: production
