language: node_js
cache: yarn
branches:
  only:
    - master
    - production
before_script:
  - chmod +x ./scripts/ci_build.sh
script:
  - yarn lint
  - yarn flow
  - yarn test
  - ./scripts/ci_build.sh
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_STAGING
    secret_access_key: $AWS_SECRET_STAGING
    bucket: staging.legislated.org
    region: us-east-2
    acl: public-read
    local_dir: dist
    skip_cleanup: true
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_PROD
    secret_access_key: $AWS_SECRET_PROD
    bucket: legislated.org
    region: us-east-2
    acl: public-read
    local_dir: dist
    skip_cleanup: true
    on:
      branch: production
