# needed to install watchman for relay-compiler
sudo: required

language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - watchman

branches:
  only:
    - master
    - production

before_script:
  - chmod +x ./scripts/ci-build.sh
  - chmod +x ./scripts/ci-watchman.sh
  - ./scrips/ci-watchman.sh

script:
  - yarn lint
  - yarn flow
  - yarn test
  - ./scripts/ci-build.sh

deploy:
  - provider: s3
    access_key_id:
      secure: "tx5h4kbHcNyvN57fsG+Ve2pmpAtWj62Pgfvc2t6h2jErAE79Ia8rw9iY0OxKaLL4vJL+OzmX9mnutL+D5QeKBuowB9Asv2wUqotBx7OxKGIBjJ5OsgOJ82eoXA80uANG3mC2ryfUzQ1f2vQjp7I63fgjTNeBuOD1FFgTjR8QPpW6bnmDiSPEIhyFPnKoe8qvtSNSirs5+PbgN6iPKfZ13fVFE59G424kq9GS3faMzLUvZHnvL4lJ6ycVCZOz+loBN/W/7j7rJaJ4r6SrQB1FycROoihCVdn96QtYimoG2cDnQJV+6GhgV+LKEoUMptUR2Zuaze6rBuRu979hN8DXxpVuYqiDVxGMLNR+ZivqTHYPGCbxwa8EMbwjsl/ADUTRTOrjJgP1GMsyZpzIp4ngNCjBJiSitW+iEWL7RujppcDDgKcms3JpmsypIQqbwbTyXyeHYVVSLBlfSRYGwLOc1GdIwDkaS7UJ9yYEnNiEI0BR3R4RpF/c4ayl0zIsZlFUiKRkL2uHlgm1PaSRzMQIq+EfEEyKmX4l4zuMh+oGQiTSFtkrZm7RFgoVVw1TAbPr3hClo8hlRxh4oS6uf9QS3Tb9dyQqXx/RgYI5uoB+XWJPLdkce0h1XDa4Ldom0xX4N20j8wChL180OuB8DPBCsO8waBI6YaVWIux1ANFb2Ik="
    secret_access_key:
      secure: "Rp19C5wiXrxmwsFlrKuj4pA+zyYr1wsnImbarcfsrl4WfezX0cTCz8+GpBIzym0OIm7gscCYo7qsvRdT1xMyvyM+JlHB2OA2VuRaK4v8DU8oeK0uXcZrRMO3L/jD4mFQTeBSOg342i1931+mBD+2/A8V7Kgv5zB+f4xlnBm/3ZnS0ip2ZkheZwE60+BBSdzvtvv1Y8vhmK77BoS7GCAvWMi28C2I1abx2AGtwxdyvy/c8EKrQSuzD98uZ5HXSwJJPEBFYBzVrzsBZzZTeWmGQBkD9IGK7NpPbm/FLGY0G9ONTv7UfQmuwohw036GLzLoUM3f5YRteTgVxr4kBt1oG1sW4lCyp8SYvY94aEdhiFcjsEKD4sF6+H4Xn9phQtIjwVw1tTAjdxYV52ieygmAcXn2Ei/IZ07ipxKAky23Jt3kbbTRkTJ2M+7cIIbRgE9AdCeaHPAXR7tyV9YRdSOksR4nc+WyUIl0DAcfYe2J7vJYFsjeQCIZ+EA5rCj0VJJ6ICxM/eRQDVycUvyxioARrGiv91pu+JHlCXb04bPtfbmi4BJrOS8j3xrSpiGI5jQhvkcO/LsicemU+F0wPLjzZFCe84n+TQIIrQuTKeJ6Z4BzMUdNZxoCRHKTEiKnHc5JdoqBn3Ss/Ey+HlmYGIz3syf/p0ygl42Pii1f8nf/iQk="
    bucket: staging.legislated.org
    region: us-east-2
    acl: public-read
    local_dir: dist
    skip_cleanup: true
    on:
      branch: master
  - provider: s3
    access_key_id:
      secure: "fdSg0qypCDp98niR/QJ35kEmfeT8KPUHFby/Xh5YCUpZCFHGBO3EDfpVvGelPdbjURpTRx467aGm4OVqTy6OaQmliBeIzyKaG3cqynUEK7fp0ax8A16T9+Hvuh9Yk9gf5YJ3TCG7X/rZYo3hX0IIiPKaXNKEE2L+v5bCqZt69Sa3oqicRVzU4G+GSLmwqSXbDIAPvsWnucTIeLB0XEhtqdeggIH6FzUIyfmFx8v/aGG0eqvoz04ANXu+WdiS93zu05AoKiCc03f0yzPrk2PkGiFdHWLtA8AdwgFqdccouhF5ikTbYYtA5o5tMDocSKO277KjuM6PEJm55/EE22PdbGqXT40JaEAbLiXAWhob3YpUrehk1xC0AjpSdT5/ctsFg2DoB06HbdiNvEbktWptfufY0fSzZHl5MsB0bpLPuPBj8TecIe5RgDe0YidlDyur3HnzFqrqvPp4uvQH9ePAXGpinQmg1bK3/yoTfqGuyuCkxqWDs6q9vLoSHAGhHsaeaGaUKwPpY0EHSuq+J/rmTzO4/3WEH923zj6YnreURLhzMatPBtxGGX2ggmvU8whVRrWQgHxvqrhum/Rvduy7e0ld6sY/VtIoV3OEgGIHhfaiBH5BW0HG3NshjmEqwgOVXw7yEWm3TOrAywUuBPdm4aKC5kKMV9GqoTJqsUwdsxI="
    secret_access_key:
      secure: "fO83tUE8rjVOezcIOXHUBl4EDd2b+JalKNH89fZWFqrskInGpiJGZ1bX+AdZ8J54ueslPWXHUyr8rNH1Hd7JZDwgAY0j7HDYw4IfQa7uhPm2HducMMY76ra+UIkiJpSoA0zEV6mNJBVLsU5GIjoSJovQA12+5GoMmaA05rV0YFq0FCpvN8NvstycDsH9+TGeJsxajh5gvaIKZyt1f8I7zUYAxcPDMUPy4g8fOhY775hkn+gp4/N+TN9YOw4T8MLpAUoyDl+BMALJUDdEsYhhgE+d8nGmLhLXluSEiQEdwu/uJWoSRBJpT7JG7D1yk9nP2TnMD8hgfVX5SbeX+XjdwRDrF3NXOvehcTFtx4pkxGV2Vl8wqcmMia9QZwo7RP4Ye3Mfo+Qh+kOfN44hT7MkV9DmOD66oI/8VVwvOEgkWExqqiRoKkYmzV16DZNAuaU/rfaNP7p57l10zrvEQ67Hl6JB37WcwlD4YtA4X8ql3FgDndLWV5R91T5VIQZiH03EK/iR0iimmKU14jIujQjHnt/SC74E1ggyRBllAhQDfY68rkb4wVIud2HAFQR/Nf4mPV/Hmnx+uRffJ/5Tr9/0Ix3c/qU21H0oadQQTAYpspRhtriRWjab3pWkIyDIV7p7o8QGPFfWGhPtnGpLBpeAgAzGxMD3WDzr/dctwJvE5bM="
    bucket: legislated.org
    region: us-east-2
    acl: public-read
    local_dir: dist
    skip_cleanup: true
    on:
      branch: production
